<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  
    <TargetFramework>net10.0</TargetFramework>
	  <NuGetAudit>false</NuGetAudit>
	  <WarningsAsErrors></WarningsAsErrors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECom.Infrastructure\ECom.Infrastructure.csproj" />
  </ItemGroup>

</Project>
